export type ResourceKey = {
  [key: string]: readonly string[];
};

export const RESOURCE_KEYS: ResourceKey = {
  appointment: [
    "status",
    "cancelationReason",
    "serviceCategory",
    "serviceType",
    "specialty",
    "appointmentType",
    "reasonCode",
    "priority",
    "description",
    "start",
    "end",
    "minutesDuration",
    "slot",
    "created",
    "comment",
    "patientInstruction",
    "participant",
    "requestedPeriod",
  ],
  encounter: [
    "status",
    "statusHistory",
    "class",
    "classHistory",
    "type",
    "serviceType",
    "priority",
    "subject",
    "episodeOfCare",
    "basedOn",
    "participant",
    "appointment",
    "period",
    "length",
    "reasonCode",
    "diagnosis",
    "hospitalization",
    "location",
  ],
  observation: [
    "status",
    "category",
    "code",
    "subject",
    "encounter",
    "effectiveDateTime",
    "issued",
    "performer",
    "valueQuantity",
    "valueCodeableConcept",
    "valueString",
    "valueBoolean",
    "valueInteger",
    "valueRange",
    "valueRatio",
    "valueSampledData",
    "valueTime",
    "valueDateTime",
    "valuePeriod",
    "interpretation",
    "note",
    "bodySite",
    "method",
    "specimen",
    "device",
    "referenceRange",
  ],
  organization: ["active", "address", "telecom", "type", "name", "contact"],
  riskassessment: [
    "status",
    "method",
    "code",
    "subject",
    "encounter",
    "occurrenceDateTime",
    "condition",
    "performer",
    "reasonCode",
    "basis",
    "prediction",
    "mitigation",
    "note",
  ],
  patient: [
    "address",
    "birthDate",
    "deceasedDateTime",
    "gender",
    "id",
    "maritalStatus",
    "name",
    "resourceType",
    "telecom",
  ],
  practitioner: [
    "active",
    "address",
    "gender",
    "id",
    "name",
    "resourceType",
    "telecom",
  ],
  diagnosticreport: [
    "category",
    "code",
    "conclusion",
    "date",
    "encounter",
    "id",
    "issued",
    "patient",
    "performer",
    "resourceType",
    "result",
    "specimen",
    "status",
    "subject",
  ],
} as const;

export type ResourceName = keyof typeof RESOURCE_KEYS;
